#### -*- Mode: Makefile -*-
#### Makefile for Darwin/PPC systems

CC=gcc
CFLAGS=-bundle -Wall
LDFLAGS=
SHLIB_SUFFIX=dylib

SDL_CFLAGS=$(CFLAGS) `sdl-config --cflags`
SDL_LDFLAGS=$(LDFLAGS) `sdl-config --libs` 

GL_CFLAGS=$(CFLAGS)
GL_LDFLAGS=$(LDFLAGS) -lobjc -framework OpenGL

SDL_TTF_CFLAGS=$(SDL_CFLAGS)
SDL_TTF_LDFLAGS=$(LDFLAGS) -lSDL_ttf

SDL_MIX_CFLAGS=$(SDL_CFLAGS)
SDL_MIX_LDFLAGS=$(LDFLAGS) -lSDL_mixer

SDL_IMG_CFLAGS=$(SDL_FLAGS)
SDL_IMG_LDFLAGS=$(LDFLAGS) -lSDL_image
