#!/bin/sh

#IFS=$'\;'
while read result error test
do
    out=$(./rameau $test)
    regexp=$(echo $out | grep -i "^\(error\|fatal\)")
    if [ "$regexp" == "" ]
    then
        echo "[OK]: rameau $test"
    else
        if [ "$error" == "err" ]
        then
            echo "[OK]: rameau $test"
        else
            echo "[ERROR]: rameau $test"
            echo "      $regexp"
        fi
    fi
done


