#!/bin/sh
cd `dirname $0`/code
cat <<EOF | cmucl
(setf extensions:*gc-verbose* nil)

(load "nile_loader")
(nile_loader:load-and-compile "nile_batali")
(nile_batali:run-simulation 	:max-cycles 25000
				:write-pop-every 5005
				:num-meanings 100
				:eta 0.01d0)
(user::quit)
EOF
