#!/bin/sh

cd `dirname $0`/code

cat <<EOF | cmucl
(setf extensions:*gc-verbose* nil)

(load "nile_loader")
(nile_loader:load-and-compile "nile_learnability")

(nile_learnability:runit)
(user::quit)
EOF
